language: python
env:
  - TEST_PACKAGE="pyclaw"
  - TEST_PACKAGE="petclaw"
python:
  - 2.7
before_install:
  - pip install coverage
  - pip install python-coveralls
  - sudo apt-get update -qq
  - sudo apt-get install -qq gfortran liblapack-pic
  - sudo apt-get install pv liblapack-dev;
  - git clone --branch=master --depth=100 --quiet git://github.com/clawpack/clawpack
  - cd clawpack
  - git submodule init
  - git submodule update clawutil visclaw riemann
  - rm -rf pyclaw
  - ln -s ../ pyclaw
install:
  - export CLAWPACK=`pwd`
  - bash ../.travis_build_stack.sh;
  - export PATH=${CLAWPACK}/stack/bin:${PATH};
  - python setup.py install;

script:
  - cd pyclaw/examples
  - if [[ "${TEST_PACKAGE}" == "pyclaw" ]]; then
       nosetests -v --with-coverage --cover-package=clawpack.pyclaw;
    fi
  - if [[ "${TEST_PACKAGE}" == "petclaw" ]]; then
       mpirun -n 4 nosetests -v;
    fi
  # Run doctests
  - cd ../src/pyclaw
  - nosetests --first-pkg-wins --with-doctest --exclude=example --exclude=limiters --exclude=sharpclaw --exclude=io


after_success:
  - coveralls

notifications:
  email: false
